_extends: .github

repository:
  name: node-api-problem
  description: HTTP Problem Utility
  topics: api,http,problem
  homepage: https://github.com/ahmadnassri/api-problem
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
