sudo: false

language: node_js

node_js:
 - 6
 - 5
 - 4

cache:
  directories:
    - node_modules

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) > /dev/null
  - npm run coverage
  - npm run codeclimate
  - declare -A PRESETS=([es2015]= ["node4"]=node4 ["node5"]=node5 ["node6"]=node6);
  - for preset in "${!PRESETS[@]}"; do BABEL_ENV=$preset npm run compile -- -d lib/${PRESETS[$preset]}; done
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
