name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 14

      - run: npx semantic-release
        working-directory: client
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
