name: release

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10, 12, 13, 14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: client-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}

      # run checks
      - run: npm audit --audit-level=moderate
      - run: npx updated
      - run: npm ci
      - run: npm run test

  release:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 14

      # release
      - run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
